#!/bin/bash

if [[ $UE_PATH == "" ]]; then
  echo "Source the ue_env_setup before running `basename $0`"
  exit 0
fi

if [[ ! -d $UE_PATH/bin ]]; then
  echo "Creating bin directory..."
  mkdir $UE_PATH/bin
fi

if [[ `ls $UE_PATH/bin | wc -l` > 0 ]]; then
  echo "Clearing out bin directory..."
  rm $UE_PATH/bin/*
fi

echo "Creating bin links..."
ln -s $UE_PATH/src/wrapper/realflow.sh $UE_PATH/bin/realflow
ln -s $UE_PATH/src/wrapper/houdini.sh $UE_PATH/bin/houdini
ln -s $UE_PATH/src/wrapper/maya.sh $UE_PATH/bin/maya
ln -s $UE_PATH/src/wrapper/nuke.sh $UE_PATH/bin/nuke
ln -s $UE_PATH/src/wrapper/mari.sh $UE_PATH/bin/mari
ln -s $UE_PATH/src/wrapper/tvpaint.sh $UE_PATH/bin/tvpaint
ln -s $UE_PATH/src/wrapper/rv.sh $UE_PATH/bin/rv
ln -s $UE_PATH/src/wrapper/rvio.sh $UE_PATH/bin/rvio
ln -s $UE_PATH/src/wrapper/ueEdit.sh $UE_PATH/bin/ueEdit
ln -s $UE_PATH/src/tools/ueAddFiles.py $UE_PATH/bin/ueAddFiles
ln -s $UE_PATH/src/tools/ueCreateAsset.py $UE_PATH/bin/ueCreateAsset
ln -s $UE_PATH/src/tools/ueCreateGroup.py $UE_PATH/bin/ueCreateGroup
ln -s $UE_PATH/src/tools/ueCreateProject.py $UE_PATH/bin/ueCreateProject
ln -s $UE_PATH/src/tools/ueDestroyVersion.py $UE_PATH/bin/ueDestroyVersion
ln -s $UE_PATH/src/tools/ueDestroyElement.py $UE_PATH/bin/ueDestroyElement
ln -s $UE_PATH/src/tools/ueDestroyAsset.py $UE_PATH/bin/ueDestroyAsset
ln -s $UE_PATH/src/tools/ueDestroyGroup.py $UE_PATH/bin/ueDestroyGroup
ln -s $UE_PATH/src/tools/ueDestroyProject.py $UE_PATH/bin/ueDestroyProject
ln -s $UE_PATH/src/tools/ueListElements.py $UE_PATH/bin/ueListElements
ln -s $UE_PATH/src/tools/ueListAssets.py $UE_PATH/bin/ueListAssets
ln -s $UE_PATH/src/tools/ueListGroups.py $UE_PATH/bin/ueListGroups
ln -s $UE_PATH/src/tools/ueListProjects.py $UE_PATH/bin/ueListProjects
ln -s $UE_PATH/src/tools/ueInfo.py $UE_PATH/bin/ueInfo
ln -s $UE_PATH/src/tools/ueTree.py $UE_PATH/bin/ueTree
ln -s $UE_PATH/src/tools/ueEditTool.py $UE_PATH/bin/ueEditTool
ln -s $UE_PATH/src/tools/ueBuildTool.py $UE_PATH/bin/ueBuildTool

echo "Done!"

